---
title: "ML - Regression"
author: "Ricardo Silva"
date: "02/09/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval=FALSE, 
                      message=FALSE, 
                      warning=FALSE)
```

```{r CLEAR EVERYTHING, eval=FALSE, include=FALSE}
# unload all non-base packages
lapply(names(sessionInfo()$otherPkgs), function(pkgs)
  detach(
    paste0('package:', pkgs),
    character.only = T,
    unload = T,
    force = T
))

rm(list=ls())
```

# Packages and initial steps

```{r load libraries, message=FALSE, warning=FALSE, include=FALSE}
# load the packages
# main packs to start with
pcks <- c('phyloseq', 'microbiome','microbiomeutilities', "patchwork",'tidymodels','tidyverse')

if(sum(as.numeric(!pcks %in% installed.packages())) != 0){
  installation <- pcks[!pcks %in% installed.packages()]
  for(i in 1:length(installation)) {
    install.packages(installation, dependencies = T)
    break()}
  suppressPackageStartupMessages(
  sapply(pcks,require,character.only = T)
) 
} else {
  suppressPackageStartupMessages(
  sapply(pcks,require,character.only = T)
) 
}

rm(pcks)
```

```{r packages and functions}
# set working directory and seed
setwd("~/R/git_hub/MH_2019/data")
folder_path <- "~/R/git_hub/MH_2019/output/"

source('~/R/git_hub/MH_2019/script/my_functions.R')
source('~/R/git_hub/MH_2019/script/theme_publication.R')
theme_set(theme_Publication_3())

# set colors
color_distance <- c("D0" = "deepskyblue2", 'D1' = 'brown1',  "D2" = "forestgreen", "D3" = "#440154FF", "D4" = "burlywood")
# color_distance1 <- c('D1' = 'brown1',  "D2" = "forestgreen", "D3" = "#440154FF", "D4" = "burlywood")
color_depth <- c('DP1'="darkorange",'DP2'="purple", "DP3" = "cyan4")
cage_control <- friendly_cols[1:3]

# check the working directory
current_directory <- getwd()
paste("Working in directory:", current_directory)

# create dir
# dir.create(paste0(folder_path,"plots/random_forest"))
# dir.create(paste0(folder_path,"data/random_forest"))
```

```{r load data}
# load object in RData format
# 16S 
# load("pseq.list.RData")
# load("pseq.list.filt.RData") # filtered data
load("pseq.list.clr.RData") # clr transformed data

# picrust
# load("pseq.fun.RData")
# load("pseq.func.filt.RData") # filtered data
load("pseq.func.clr.RData") # clr transformed data

```


# 2 - Random forest

```{r set model}
# Specify the model and engine
rf_model <- 
  rand_forest(mtry = tune(), 
              min_n = tune(), 
              trees = 501) %>% 
  set_mode("regression")  %>%
   set_engine("randomForest", 
               importance = TRUE) 

```

```{r big function}
# big function of model fitting and predicting
predict_rf <- function(df, variable) {
# prepare the data
# join datasets
df <- df %>% 
  left_join(meta.table %>% 
              select(sample_id, variable)) %>%
  select(-sample_id) %>%
  rename(variable = variable)

# Split into train/test
# split each data into training (75%) and testing (25%)
df_split <- df %>% initial_split(prop = 3/4)

# extract training and testing sets
df_train <- df_split %>% training
df_test <- df_split %>% testing

# create CV object from training data
df_cv <- df_train %>% vfold_cv(v = 10, repeats = 3)

# Define a recipe
rf_rec <- 
  recipe(formula = variable ~ ., data = df_train) %>%
  # normalize the data (center and scale all predictors = mean to zero and standard deviation of one)
  step_normalize(all_predictors())

# set workflow
rf_workflow <- workflow() %>%
  # add the model
  add_model(rf_model) %>%
  # add recipe
  add_recipe(rf_rec)

# training and tune
rf_tune_results_rf <- rf_workflow %>%
  tune_grid(resamples = df_cv, #CV object
            grid = 20, # grid of values to try
            control = control_grid(save_pred = T),
            metrics = metric_set(rmse, rsq)
            )

# Finalize workflow
final_rf <- rf_workflow %>%
  finalize_workflow(select_best(rf_tune_results_rf, "rmse"))

# Evaluate the model on the test set
# fit
# rf_rs <-
#   fit_resamples(final_rf,
#     resamples = df_cv,
#     control = control_resamples(save_pred = TRUE)
#   )

# last fit
# will train the model using training data, and produce evaluations based on the test set
rf_fit <- final_rf %>%
  # fit on the training set and evaluate on test set
  last_fit(df_split)

# evaluating
test_performance <- rf_fit %>% collect_metrics()
rmse <- test_performance %>% 
  slice(1) %>% 
  pull(.estimate) %>% 
  round(.,2)
r2 <- test_performance %>% 
  slice(2) %>% 
  pull(.estimate) %>% 
  round(.,3)

# generate predictions from the test set
#test_predictions <- rf_fit %>% collect_predictions()
pred.plot <- rf_fit %>% 
  collect_predictions() %>%
  ggplot(aes(variable, .pred)) +
  geom_abline(color = "darkorange3", size = 1) +
  geom_point(alpha = 0.5, color = "midnightblue") +
  labs(x = glue::glue("{variable}"),
       y = glue::glue("predicted {variable}"), 
       subtitle = glue::glue("RMSE = ", rmse, ", R2 = ", r2))

# ROC curve
# roc <- rf_fit %>% 
#   collect_predictions() %>% 
#   roc_curve(children, .pred_children) %>% 
#   autoplot()

# Variable importance
# graph
plot.vip <- rf_fit %>%
  extract_fit_parsnip() %>%
  vip::vip(aesthetics = list(alpha = 0.8, fill = "midnightblue"))

# table
table.vip <- rf_fit %>%
  extract_fit_parsnip() %>%
  vip::vi() %>%
  rename(ASV = Variable) %>%
  left_join(tax.df)

return(list(test_performance, pred.plot, plot.vip, table.vip))

}
```

## run model - 16s

### ASVs diff abundant
```{r}
# 16s
aldex_16s <-
  read_csv(paste0(folder_path,"data/feature_selection/16s_aldex.csv"))

deseq_16s <-
  read_csv(paste0(folder_path,"data/feature_selection/16s_deseq.csv"))

# aldex_16s %>% 
#   filter(effect < -1.5 | effect > 1.5) %>%
#   full_join(deseq_16s, by="ASV") %>%
#   filter(if_any(everything(), ~str_detect(., "Psychro"))) %>%
#   select(Phylum.x:Genus.x, Phylum.y:Genus.y)

ASVs_select <- aldex_16s %>% 
  filter(effect < -1.5 | effect > 1.5) %>%
  full_join(deseq_16s, by="ASV") %>%
  filter(str_detect(ASV, "b_")) %>%
  mutate(ASV = sort(ASV)) %>%
  distinct(ASV) %>%
  pull
```

### Cleaning
```{r}
# Pull out the information and clean up the data
pseq <- pseq.list.clr[[2]]
# Clust contains the samples we want to keep
paste("There are", ntaxa(pseq), "ASVs in the dataset.")
paste("There are", nsamples(pseq), "samples in the dataset.")

tax.df <- pseq %>% 
  get_tibble("tax_table", column_id = "ASV")

kingdom <- pseq %>%  
  get_tibble("tax_table", column_id = "ASV") %>% 
  pull(Kingdom) %>% 
  unique()
```

### Prepare data before running the model
```{r prepare data}
# get ASV table
clr_otu <- pseq %>% 
  get_tibble("otu_table", column_id = "ASV") %>%
  filter(ASV %in% ASVs_select)

clr_otu <- clr_otu %>% 
  column_to_rownames("ASV") %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("sample_id") %>% tibble

# meta table
meta.table <-  pseq %>% 
  get_tibble("sam_data", column_id = "sample_id")

```


```{r}
set.seed(2021)
# variables
# vars <- c("NOX", "NH4", "oxygen", "turbidity")

# doParallel
cores <- parallel::detectCores(logical = FALSE)
cl <- parallel::makePSOCKcluster(cores)
doParallel::registerDoParallel(cores = cl)

# run the function for each variable
rf_NH4 <- predict_rf(clr_otu, "NH4")
rf_NOX <- predict_rf(clr_otu, "NOX")
# rf_oxygen <- predict_rf(clr_otu, "oxygen")
rf_turb <- predict_rf(clr_otu, "turbidity")

# model performance
rf_NH4[[1]] %>%
  mutate(env_par = "NH4") %>%
  bind_rows(rf_NOX[[1]] %>% 
  mutate(env_par = "NOX"),
  # rf_oxygen[[1]] %>% 
  # mutate(env_par = "oxygen"),
  rf_turb[[1]] %>% 
  mutate(env_par = "turbidity")) %>%
  write_csv(paste0(folder_path,'data/random_forest/rmse_r2_16s.csv'))

# values vs predicted values
predicted.plots <- rf_NH4[[2]] + rf_NOX[[2]] + rf_turb[[2]] + plot_annotation(title = "Bacterial Community")
# predicted.plots <- rf_NH4[[2]] + rf_NOX[[2]] + rf_oxygen[[2]] + rf_turb[[2]] + plot_annotation(title = "Bacterial Community")

ggsave(predicted.plots , filename = paste0(folder_path, "plots/random_forest/value_predicted_16s.tiff"), compression = "lzw")

# save table with vip ASV
rf_NH4[[4]] %>%
  mutate(env_par = "NH4") %>%
  bind_rows(rf_NOX[[4]] %>% 
  mutate(env_par = "NOX"),
  # rf_oxygen[[4]] %>% 
  # mutate(env_par = "oxygen"),
  rf_turb[[4]] %>% 
  mutate(env_par = "turbidity")) %>%
  write_csv(paste0(folder_path,'data/random_forest/vip_16s.csv'))


# vip_16s <- read_csv(paste0(folder_path,'data/random_forest/vip_16s.csv')) %>%
#   mutate(env_par = case_when(env_par == "turbidiy" ~ "turbidity",
#                              TRUE ~ as.character(env_par)))
# 
# 
# write_csv(vip_16s, paste0(folder_path,'data/random_forest/vip_16s1.csv'))
# 
# vip_16s %>%
#   filter(env_par %in% c("NH4","NOX", "turbidity")) %>%
#   group_by(env_par) %>%
#   slice_max(Importance, n = 20) %>%
#   write_csv(paste0(folder_path,'data/random_forest/vip_16s_top20.csv'))

```

## run model - picrust

### pathways diff abundant
```{r}
# picrust
aldex_picrust <-
  read_csv(paste0(folder_path,"data/feature_selection/picrust_aldex.csv"))

deseq_picrust <-
  read_csv(paste0(folder_path,"data/feature_selection/picrust_deseq.csv"))

ASVs_select <- aldex_picrust %>% 
  filter(effect < -1.5 | effect > 1.5) %>%
  full_join(deseq_picrust, by="ASV") %>%
  mutate(ASV = sort(ASV)) %>%
  distinct(ASV) %>%
  pull
```

### cleaning
```{r}
# Pull out the information and clean up the data
pseq <- pseq.func.clr
# Clust contains the samples we want to keep
paste("There are", ntaxa(pseq), "ASVs in the dataset.")
paste("There are", nsamples(pseq), "samples in the dataset.")

tax.df <- pseq %>% 
  get_tibble("tax_table", column_id = "ASV")

kingdom <- "Functional Annotations"
```

### Prepare data before running the model
```{r prepare data}
# get ASV table
clr_otu <- pseq %>% 
  get_tibble("otu_table", column_id = "ASV") %>%
  filter(ASV %in% ASVs_select)

clr_otu <- clr_otu %>% 
  column_to_rownames("ASV") %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("sample_id") %>% tibble

# meta table
meta.table <-  pseq %>% 
  get_tibble("sam_data", column_id = "sample_id")

```

```{r}
set.seed(2021)
# variables
# vars <- c("NOX", "NH4", "oxygen", "turbidity")

# doParallel
cores <- parallel::detectCores(logical = FALSE)
cl <- parallel::makePSOCKcluster(cores)
doParallel::registerDoParallel(cores = cl)

# run the function for each variable
# rf_NH4 <- predict_rf(clr_otu, "NH4")
rf_NOX <- predict_rf(clr_otu, "NOX")
# rf_oxygen <- predict_rf(clr_otu, "oxygen")
rf_turb <- predict_rf(clr_otu, "turbidity")


# values vs predicted values
predicted.plots <- rf_NOX[[2]] + rf_turb[[2]] + plot_annotation(title = "Functional Annotations")
# predicted.plots <- rf_NH4[[2]] + rf_NOX[[2]] + rf_oxygen[[2]] + rf_turb[[2]] + plot_annotation(title = "Functional Annotations")

ggsave(predicted.plots , filename = paste0(folder_path, "plots/random_forest/value_predicted_picrust.tiff"), compression = "lzw")

# models performance
rf_NH4[[1]] %>%
  mutate(env_par = "NH4") %>%
  bind_rows(rf_NOX[[1]] %>% 
  mutate(env_par = "NOX"),
  rf_oxygen[[1]] %>% 
  mutate(env_par = "oxygen"),
  rf_turb[[1]] %>% 
  mutate(env_par = "turbidity")) %>%
  write_csv(paste0(folder_path,'data/random_forest/rmse_r2_picrust.csv'))

# save table with vip ASV
rf_NH4[[4]] %>%
  mutate(env_par = "NH4") %>%
  bind_rows(rf_NOX[[4]] %>% 
  mutate(env_par = "NOX"),
  rf_oxygen[[4]] %>% 
  mutate(env_par = "oxygen"),
  rf_turb[[4]] %>% 
  mutate(env_par = "turbidity")) %>%
  write_csv(paste0(folder_path,'data/random_forest/vip_picrust.csv'))

# vip_picrust <- read_csv(paste0(folder_path,'data/random_forest/vip_picrust.csv')) %>%
#   left_join(eric_2021) %>%
#   mutate(Super.classes = coalesce(Super.classes, pathway),
#          env_par = case_when(env_par == "turbidiy" ~ "turbidity",
#                              TRUE ~ as.character(env_par)))
# 
# 
# write_csv(vip_picrust, paste0(folder_path,'data/random_forest/vip_picrust1.csv'))
# 
# vip_picrust %>% 
#   filter(env_par %in% c("NOX", "turbidity")) %>%
#   group_by(env_par) %>%
#   slice_max(Importance, n = 20) %>%
#   write_csv(paste0(folder_path,'data/random_forest/vip_picrust_top20.csv'))
```

## Bar plot

#### 16s
```{r}
vip_16s <-  read_csv(paste0(folder_path,'data/random_forest/vip_16s.csv'))

# filter only variables found in db-RDA
vip_16s <- vip_16s %>% filter(env_par %in% c("NH4","NOX", "turbidiy")) %>%
  mutate(env_par = case_when(env_par == "turbidiy" ~ "turbidity",
         TRUE ~ as.character(env_par)))

imp_plot <- function(df){
imp_plot <- df %>%
  mutate(name = fct_reorder(ASV, Importance),
         label = str_c(Phylum, Class, Family, Genus, sep = "_"),
         label = str_remove(label, c("_unknown", "unknown_"))) %>%
  slice_head(n=10) %>%
  ggplot(aes(x=name, y=Importance)) +
    geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
    geom_text(aes(label = label), y=0.1, hjust=0, fontface = "italic") +
    coord_flip() +
    xlab("")
  return(imp_plot)
}

# nest_vip_line <- rf_NH4[[4]] %>%
#   mutate(env_par = "NH4") %>%
#   bind_rows(rf_NOX[[4]] %>% 
#   mutate(env_par = "NOX"),
#   rf_oxygen[[4]] %>% 
#   mutate(env_par = "oxygen"),
#   rf_turb[[4]] %>% 
#   mutate(env_par = "turbidity")) %>%
#   group_by(env_par) %>%
#   nest %>%
#   mutate(plots = map2(data, env_par, ~imp_plot(.x) + 
#                         ggtitle(paste(.y))
#                       ))


# vip_16s <- wrap_plots(nest_vip_line$plots) + plot_annotation(title = "Bacterial Community")
# ggsave(vip_16s, filename = paste0(folder_path,"plots/random_forest/vip_rf_16s.tiff"), compression = "lzw", width = 21, height = 12)
# 
# walk2(nest_vip_line$env_par, nest_vip_line$plots,
#     ~ggsave(filename = paste0(folder_path,"plots/random_forest/vip_rf_",.x, ".tiff"), 
#             plot = .y, 
#             compression = "lzw"))


vip.plot <- vip_16s %>% 
  group_by(env_par) %>%
  nest %>%
  mutate(plots = map2(data, env_par, ~imp_plot(.x) + 
                        ggtitle(paste(.y))
                      ))

vip_picrust <- wrap_plots(vip.plot$plots, nrow = 2) + plot_annotation(title = "Bacterial Community")
ggsave(vip_picrust, filename = paste0(folder_path,"plots/random_forest/vip_rf_16s.tiff"), compression = "lzw", width = 14, height = 11)


```

#### picrust
```{r}
# Eric 2021
eric_2021 <- read_csv("eric_2021.csv") %>% rename(ASV = MetaCyc) %>% select(ASV, Super.classes)
#eric_2021 %>% filter(if_any(everything(), ~str_detect(.,"Secondary")))
vip_picrust <-  read_csv(paste0(folder_path,'data/random_forest/vip_picrust.csv')) %>%
  left_join(eric_2021) %>%
  # replace NAs
  mutate(Super.classes = coalesce(Super.classes, pathway))

# filter only variables found in db-RDA
vip_picrust <- vip_picrust %>% filter(env_par %in% c("NOX", "turbidiy")) %>%
  mutate(env_par = case_when(env_par == "turbidiy" ~ "turbidity",
         TRUE ~ as.character(env_par)))
  
# function
imp_plot <- function(df){
imp_plot <- df %>%
  mutate(name = fct_reorder(ASV, Importance),
         label = str_c(pathway, description, sep = "_"),
         label = str_to_title(label)) %>%
  slice_head(n=10) %>%
  ggplot(aes(x=name, y=Importance)) +
    geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
    geom_text(aes(label = Super.classes), y=0.1, hjust=0) +
    coord_flip() +
    xlab("")
  return(imp_plot)
}

# nest_vip_line <- rf_NH4[[4]] %>%
#   mutate(env_par = "NH4") %>%
#   bind_rows(rf_NOX[[4]] %>% 
#   mutate(env_par = "NOX"),
#   rf_oxygen[[4]] %>% 
#   mutate(env_par = "oxygen"),
#   rf_turb[[4]] %>% 
#   mutate(env_par = "turbidiy")) %>%
#   group_by(env_par) %>%
#   nest %>%
#   mutate(plots = map2(data, env_par, ~imp_plot(.x) + 
#                         ggtitle(paste(.y))
#                       ))

vip.plot <- vip_picrust %>% 
  group_by(env_par) %>%
  nest %>%
  mutate(plots = map2(data, env_par, ~imp_plot(.x) + 
                        ggtitle(paste(.y))
                      ))

vip_picrust <- wrap_plots(vip.plot$plots) + plot_annotation(title = "Functional Annotations")
ggsave(vip_picrust, filename = paste0(folder_path,"plots/random_forest/vip_rf_picrust.tiff"), compression = "lzw", width = 17, height = 8.5)


walk2(nest_vip_line$env_par, nest_vip_line$plots,
    ~ggsave(filename = paste0(folder_path,"plots/random_forest/vip_rf_picrust_",.x, ".tiff"), 
            plot = .y, 
            compression = "lzw"))


```

## Ternary

### 16s
```{r}
# https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggtern/
# https://online.ucpress.edu/elementa/article/9/1/00111/116754/Protist-communities-along-freshwater-marine

vip_16s <-  read_csv(paste0(folder_path,'data/random_forest/vip_16s.csv'))

tern_plot_rf <- function(pseq, env_par, n_importance)
  {
  tax_df <- pseq %>% 
    get_tibble("tax_table", column_id = "ASV")

  name_taxa <- tax_df %>% unite("Taxa", Phylum, Class, sep = "_")
  n <- length(levels(as.factor(name_taxa$Taxa)))
  my_colors <- tibble(colors = friendly_cols[1:n],
                      name_taxa %>% distinct(Taxa))
  
  Kingdom <- tax_df %>% distinct(Kingdom) %>% pull
  
  tern_df <- pseq %>% 
    transform("compositional") %>%
    psmelt.dplyr() %>%
    rename(ASV = OTU)
 
  asv_rf <- vip_16s %>% filter(env_par == !!(env_par)) %>% slice_max(Importance, n= n_importance) %>% distinct(ASV) %>% pull

  tern_df_dp <- tern_df %>%
 #   filter(Depth == !!(Depth)) %>% 
    group_by(ASV, site) %>% 
    summarise(value = mean(Abundance)) %>% 
    filter(ASV %in% asv_rf) %>%
    pivot_wider(c(ASV), names_from = "site", values_from = "value") %>%
    mutate(sum = rowSums(across(where(is.numeric)))) %>%
    filter(sum > 0) %>%
    left_join(tax_df) %>%
    mutate(Taxa = str_c(Phylum, Class,sep = "_"),
           ASV = str_remove(ASV, "b_asv_")) %>%
    left_join(my_colors)
  
  col <- as.character(tern_df_dp$colors)
  names(col) <- as.character(tern_df_dp$Taxa)
  
  abund_tern <- tern_df_dp %>%
    select(-Kingdom, -Taxa) %>%
    group_by(ASV, Phylum,Class,Order,Family,Genus) %>%
    summarise(Control = Control/sum,
              lease_1 = lease_1/sum,
              lease_2 = lease_2/sum) %>%
    mutate(env_par = env_par)
  
  # max <- tern_df_dp %>% 
  #   left_join(tern_df_dp  %>%
  #                select(ASV, cage_1, cage_2, Control) %>%
  #                pivot_longer(!ASV, names_to = 'max_site', values_to = 'value') %>%
  #                group_by(ASV) %>%
  #                 # If you're worried about keeping ties:
  #                slice(which.max(value))
  #              ) %>%
  #   dplyr::select(ASV, max_site, Phylum:Genus)
  
  # plot
  n  = length(tern_df_dp$ASV)   #Number of Data Points
  nv = 0.015  #Vertical Adjustment
  pn = position_nudge_tern(y=nv,x=-nv/2,z=-nv/2)
  
  plot <- tern_df_dp %>%
    ggtern(aes(x = lease_1, y = Control, z = lease_2)) + 
    geom_point(aes(size=(lease_1 + lease_2 + Control), color = Taxa)) +
    theme_Publication_3() +
    theme_showarrows() +
    theme_nomask() + #Allow Labels to Spool Over Edges
    geom_Lline(Lintercept=0.60,color="red") +
    geom_Tline(Tintercept=.6, colour='red') + 
    geom_Rline(Rintercept=.6, colour='red') +
    #  geom_text(position = pn, aes(label = ASV), check_overlap = T, hjust = 1, vjust = 1) +
    scale_size(name="Mean Relative Abundance") +
    scale_color_manual(name = "Phylum_Class", values = col, 
                       guide = guide_legend(label.theme = element_text(angle = 0, face = "italic"))) +
    labs(title = paste(env_par)) + 
    theme(plot.title = element_text(hjust=0.5))
  
  return(list(plot, abund_tern))
}
```


```{r}
# prepare the data
load("pseq.list.filt.RData") # filtered data
# plot ternary plots

vip_nox <- tern_plot_rf(pseq.list.filt[[2]], 
                             env_par = "NOX", 
                             n_importance = 10) 
vip_nh4 <- tern_plot_rf(pseq.list.filt[[2]], 
                             env_par = "NH4", 
                             n_importance = 10) 
vip_turb <- tern_plot_rf(pseq.list.filt[[2]], 
                             env_par = "turbidity", 
                             n_importance = 10)  

# make a dataframe
df_vip_16s <- bind_rows(vip_nox[[2]], vip_nh4[[2]], vip_turb[[2]])
df_vip_16s %>% write_csv(paste0(folder_path,"data/random_forest/tern_vip_rf_16s.csv"))


# make a common legend
df_colors <- bind_rows(vip_nox[[1]]$data %>% distinct(Taxa, colors),
                       vip_nh4[[1]]$data %>% distinct(Taxa, colors),
                       vip_turb[[1]]$data %>% distinct(Taxa, colors)) %>%
    distinct(Taxa, colors)

col <- as.character(df_colors$colors)
names(col) <- as.character(df_colors$Taxa)

# make a simple plot and get the legend
plot <- df_colors %>% 
  mutate(n = 1) %>%  
  ggplot(aes(n, Taxa, color = Taxa)) +
  geom_point() +
  scale_color_manual(name = "Phylum_Class", values = col,
                     guide = guide_legend(label.theme = element_text(angle = 0, face = "italic"))) + theme_Publication_3()
# get legend using ggpubr
legend <- ggpubr::get_legend(plot)

# without legens
a <- vip_nox[[1]]  + theme(legend.position = "none") 
b <- vip_nh4[1]  + theme(legend.position = "none") 
c <- vip_turb[[1]] + theme(legend.position = "none")

# plotmusing grid.arrange
layout_matrix <- matrix(c(1, 2, 3, 4), nrow = 2, byrow = TRUE)
grid.arrange(a, b, c, legend, layout_matrix = layout_matrix)

# save as pdf (15.32 x 9.8 in)

```

### picrust
```{r}
# Eric 2021
eric_2021 <- read_csv("eric_2021.csv") %>% rename(ASV = MetaCyc) %>% select(ASV, Super.classes)
#eric_2021 %>% filter(if_any(everything(), ~str_detect(.,"Secondary")))
vip_picrust <-  read_csv(paste0(folder_path,'data/random_forest/vip_picrust.csv')) %>%
  left_join(eric_2021) %>%
  # replace NAs
  mutate(Super.classes = coalesce(Super.classes, pathway))

# filter only variables found in db-RDA
vip_picrust <- vip_picrust %>% 
  filter(env_par %in% c("NOX", "turbidiy")) %>%
  mutate(env_par = case_when(env_par == "turbidiy" ~ "turbidity",
         TRUE ~ as.character(env_par)))

tern_plot_picrust_rf <- function(pseq, env_par, n_importance)
  {
  tax_df <- pseq %>% 
  get_tibble("tax_table", column_id = "ASV") %>%
  left_join(eric_2021) %>%
  # replace NAs
  mutate(Super.classes = coalesce(Super.classes, pathway))

n <- length(levels(as.factor(tax_df$Super.classes)))
my_colors <- tibble(colors = friendly_cols[1:n],
                    tax_df %>% distinct(Super.classes))

Kingdom <- "Functional Annotations"

tern_df <- pseq %>% 
    transform("compositional") %>%
    psmelt.dplyr() %>%
    rename(ASV = OTU)

asv_rf <- vip_picrust %>% 
  filter(env_par == !!(env_par)) %>% 
  slice_max(Importance, n= n_importance) %>% distinct(ASV) %>% pull


tern_df_dp <- tern_df %>%
    group_by(ASV, site) %>% 
    summarise(value = mean(Abundance)) %>% 
    filter(ASV %in% asv_rf) %>%
    pivot_wider(c(ASV), names_from = "site", values_from = "value") %>%
  mutate(sum = rowSums(across(where(is.numeric)))) %>%
  filter(sum > 0) %>%
  left_join(tax_df) %>%
  left_join(my_colors)

abund_tern <- tern_df_dp %>% 
  group_by(ASV, description, pathway, Super.classes, ontology) %>%
  summarise(Control = Control/sum,
            lease_1 = lease_1/sum,
            lease_2 = lease_2/sum) %>%
    mutate(env_par = env_par)

col <- as.character(tern_df_dp$colors)
names(col) <- as.character(tern_df_dp$Super.classes)

# plot
n  = length(tern_df_dp$ASV)   #Number of Data Points
nv = 0.015  #Vertical Adjustment
pn = position_nudge_tern(y=nv,x=-nv/2,z=-nv/2)

plot <- tern_df_dp %>%
  mutate_if(is.character, as.factor) %>%
  ggtern(aes(x = lease_1, y = Control, z = lease_2)) + 
  geom_point(aes(size=(lease_1 + lease_2 + Control), color = Super.classes)) +
  theme_Publication_3() +
  theme_showarrows() +
  theme_nomask() + #Allow Labels to Spool Over Edges
  geom_Lline(Lintercept=0.60,color="red") +
  geom_Tline(Tintercept=.6, colour='red') + 
  geom_Rline(Rintercept=.6, colour='red') +
#  geom_text(position = pn, aes(label = pathway), check_overlap = T, hjust = 1, vjust = 1) +
  scale_size(name="Mean Relative Abundance")+
  scale_color_manual(name = "pathway", values = col) +
  labs(title = paste(env_par)) + 
  theme(plot.title = element_text(hjust=0.5))

  
  return(list(plot, abund_tern))
}
```


```{r}
# prepare the data
load("pseq.func.filt.RData") # filtered data
# plot ternary plots

vip_nox <- tern_plot_picrust_rf(pseq.func.filt, 
                             env_par = "NOX", 
                             n_importance = 10) 
vip_turb <- tern_plot_picrust_rf(pseq.func.filt, 
                             env_par = "turbidity", 
                             n_importance = 10) 

# make a dataframe
df_vip_picrust <- bind_rows(vip_nox[[2]],vip_turb[[2]])
df_vip_picrust %>% write_csv(paste0(folder_path,"data/random_forest/tern_vip_rf_picrust.csv"))

# make a common legend
df_colors <- bind_rows(vip_nox[[1]]$data %>% distinct( Super.classes , colors),
                       vip_turb[[1]]$data %>% distinct( Super.classes , colors)) %>%
    distinct( Super.classes , colors)

col <- as.character(df_colors$colors)
names(col) <- as.character(df_colors$ Super.classes )

# make a simple plot and get the legend
plot <- df_colors %>% 
  mutate(n = 1) %>%  
  ggplot(aes(n,  Super.classes , color =  Super.classes )) +
  geom_point() +
  scale_color_manual(name = "Super Classes", 
                     values = col,
                     guide = guide_legend(label.theme = element_text(angle = 0, face = "italic"))) +
  guides(color=guide_legend(nrow=3, col = 3, byrow=TRUE)) +
  theme_Publication_3()
# get legend using ggpubr
legend <- ggpubr::get_legend(plot)

# without legens
a <- vip_nox[[1]] + theme(legend.position = "none") 
b <- vip_turb[[1]]  + theme(legend.position = "none") 


# plotmusing grid.arrange
layout_matrix <- matrix(c(1, 1, 2, 2, 3, 3,3,3 ), nrow = 2, byrow = TRUE)
grid.arrange(a , b,  legend, layout_matrix = layout_matrix)

# save as pdf (15.32 x 9.8 in)

```

## Distance profile - top 5 VIP

```{r}
# function to plot the top 9 VIPs ASVs
rf_distance <- function(pseq, ASV_rf, nuts){
pseq <- pseq

tax_df <- pseq %>% 
  get_tibble("tax_table", column_id = "ASV")

# lease 1
pseq1 <- pseq %>% 
  subset_samples(site %in% c('lease_1', 'Control'))
otu_df1 <- pseq1 %>% 
  get_tibble("otu_table", column_id = "ASV")

otu_rf1 <- otu_df1 %>% 
  filter(ASV %in% ASV_rf) %>%
  column_to_rownames("ASV") 
tax_rf1 <- tax_df %>% 
  filter(ASV %in% ASV_rf)  %>%
  column_to_rownames("ASV")

phy_rf_lease1 <- phyloseq(otu_table(as.matrix(as.data.frame(otu_rf1)), taxa_are_rows = TRUE),
                     tax_table(as.matrix(tax_rf1)), sample_data(meta_lease1))

rf_df_1 <- phy_rf_lease1 %>% 
  psmelt.dplyr() %>%
  rename(ASV = OTU) 


p_l1 <- rf_df_1  %>%
    mutate(ASV = factor(ASV, ASV_rf),
      Distance_m = round(Distance_m, 1),
           Distance_m = as.factor(Distance_m)) %>% 
  ggplot(aes(x = Distance_m, y = Abundance, group = Depth)) + 
    geom_jitter(aes(color = Depth),
                alpha = 0.6,
                show.legend = T, 
                width = 0.1) + 
#    geom_line(aes(linetype = Depth, color = Depth)) +
    stat_smooth(aes(color = Depth),
                se = F, size = 1,
                show.legend = F, alpha = 0.3) +
    # scale_color_manual(values = asvvarpal, labels = asvvarlabels) + 
    # scale_x_continuous(breaks = cumnum,
    #                    name = 'Month',
    #                    labels = str_to_title(month.order)) +
    facet_wrap(~ASV, scales = "free_y") + 
    ylab('Centered log ratio') +
    scale_color_manual(labels = unique(meta$Depth1), values = c(color_depth)) +
    geom_vline(xintercept = '82.8', linetype="dashed", color = "red") +
    ggtitle(paste0('Lease 1: ', nuts)) +
  theme(legend.position = "bottom",
        strip.text = element_text(face = "italic"))

# lease 2
pseq2 <- pseq %>% 
  subset_samples(site %in% c('lease_2', 'Control'))
otu_df2 <- pseq2 %>% 
  get_tibble("otu_table", column_id = "ASV")

otu_rf2 <- otu_df2 %>% 
  filter(ASV %in% ASV_rf) %>% 
  column_to_rownames("ASV")
tax_rf2 <- tax_df %>% 
  filter(ASV %in% ASV_rf)  %>%
  column_to_rownames("ASV")

phy_rf_lease2 <- phyloseq(otu_table(as.matrix(as.data.frame(otu_rf2)), taxa_are_rows = TRUE),
                     tax_table(as.matrix(tax_rf2)), sample_data(meta_lease2))

rf_df_2 <- phy_rf_lease2 %>% 
  psmelt.dplyr() %>%
  rename(ASV = OTU) 

p_l2 <- rf_df_2  %>%
    mutate(ASV = factor(ASV, ASV_rf),
           Distance_m = round(Distance_m, 1),
           Distance_m = as.factor(Distance_m)) %>% 
  ggplot(aes(x = Distance_m, y = Abundance, group = Depth)) + 
    geom_jitter(aes(color = Depth),
                alpha = 0.6,
                show.legend = T, 
                width = 0.1) + 
#    geom_line(aes(linetype = Depth, color = Depth)) +
    stat_smooth(aes(color = Depth),
                se = F, size = 1,
                show.legend = F, alpha = 0.3) +
    # scale_color_manual(values = asvvarpal, labels = asvvarlabels) + 
    # scale_x_continuous(breaks = cumnum,
    #                    name = 'Month',
    #                    labels = str_to_title(month.order)) +
    # facet_wrap(~str_c(ASV,Class, Family, Genus, sep = '_'), scales = "free_y") + 
    facet_wrap(~ASV, scales = "free_y") +
    ylab('Centered log ratio') +
    scale_color_manual(labels = unique(meta$Depth1), values = c(color_depth)) +
    geom_vline(xintercept = '84.2', linetype="dashed", color = "red") +
    ggtitle(paste0('Lease 2: ', nuts)) +
  theme(legend.position = "bottom",
        strip.text = element_text(face = "italic"))

return(list(p_l1, p_l2))
}
```

### 16s
```{r}
# split meta data 
meta_lease2 <- read_csv(paste0(getwd(),"/meta_lease2.csv")) %>% column_to_rownames("sample_id")
meta_lease1 <- read_csv(paste0(getwd(),"/meta_lease1.csv")) %>% column_to_rownames("sample_id")

# get the VIP table
bac.vip <- read_csv(paste0(folder_path,'data/random_forest/vip_16s.csv'))
ASV_list <- bac.vip %>% 
  group_by(env_par) %>% 
  slice_head(n = 9) %>%
  split(.$env_par) %>% 
  map(., ~mutate(.,ASV = fct_reorder(ASV, desc(Importance)))) %>%
  map(., ~distinct(.,ASV) %>% pull(ASV))

# map the top 9 ASVs for each environmental parameter
asv_vip_plots <- ASV_list %>% 
  map2(.,names(.),~rf_distance(pseq.list.clr[[2]],.x,.y))

nh4_asv_vip <- wrap_plots(asv_vip_plots[[1]]) + plot_layout(guides = "collect") & theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(nh4_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_NH4.tiff"), compression = "lzw", width = 13.3, height = 8.4)

nox_asv_vip <-wrap_plots(asv_vip_plots[[2]]) + plot_layout(guides = "collect")& theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(nox_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_NOX.tiff"), compression = "lzw", width = 13.3, height = 8.4)

oxy_asv_vip <-wrap_plots(asv_vip_plots[[3]]) + plot_layout(guides = "collect") & theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(oxy_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_o2.tiff"), compression = "lzw", width = 13.3, height = 8.4)

turb_asv_vip <-wrap_plots(asv_vip_plots[[4]]) + plot_layout(guides = "collect") & theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(turb_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_turb.tiff"), compression = "lzw", width = 13.3, height = 8.4)

```

### Picrust
```{r}
# split meta data 
meta_lease2 <- read_csv(paste0(getwd(),"/meta_lease2.csv")) %>% column_to_rownames("sample_id")
meta_lease1 <- read_csv(paste0(getwd(),"/meta_lease1.csv")) %>% column_to_rownames("sample_id")

# get the VIP table
picrust.vip <- read_csv(paste0(folder_path,'data/random_forest/vip_picrust.csv'))
ASV_list <- picrust.vip %>% 
  group_by(env_par) %>% 
  slice_head(n = 9) %>%
  split(.$env_par) %>% 
  map(., ~mutate(.,ASV = fct_reorder(ASV, desc(Importance)))) %>%
  map(., ~distinct(.,ASV) %>% pull(ASV))

# map the top 9 ASVs for each environmental parameter
asv_vip_plots_picrust <- ASV_list %>% 
  map2(.,names(.),~rf_distance(pseq.func.clr,.x,.y))

nh4_asv_vip <- wrap_plots(asv_vip_plots_picrust[[1]]) + plot_layout(guides = "collect") & theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(nh4_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_NH4_picrust.tiff"), compression = "lzw", width = 13.3, height = 8.4)

nox_asv_vip <-wrap_plots(asv_vip_plots_picrust[[2]]) + plot_layout(guides = "collect")& theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(nox_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_NOX_picrust.tiff"), compression = "lzw", width = 13.3, height = 8.4)

oxy_asv_vip <-wrap_plots(asv_vip_plots_picrust[[3]]) + plot_layout(guides = "collect") & theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(oxy_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_o2_picrust.tiff"), compression = "lzw", width = 13.3, height = 8.4)

turb_asv_vip <-wrap_plots(asv_vip_plots_picrust[[4]]) + plot_layout(guides = "collect") & theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, size = 8))
ggsave(turb_asv_vip, filename = paste0(folder_path, "plots/random_forest/distance_vip_turb_picrust.tiff"), compression = "lzw", width = 13.3, height = 8.4)
```


## box plot
```{r}
# VIP ASVs
pseq <- pseq.list.clr[[2]]

box_vip <- function(df){
  box1 <- df %>% 
    slice_head(n=10) %>% 
    left_join(pseq %>% psmelt.dplyr() %>% 
                rename(ASV = OTU)) %>% 
    mutate(ASV = str_remove(ASV, "b_asv_")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(ASV = fct_inorder(ASV)) %>%
    ggplot(aes(site, Abundance, fill = site)) +
    geom_jitter(alpha = 0.5, width = 0.1) +
    geom_boxplot(alpha = 0.5) +
    scale_fill_manual(values = cage_control) +
    labs(y = "Abundance (CLR)") +
    theme(axis.title.x = element_blank()) +
  #  scale_color_manual(values = cage_control) +
    facet_grid(ASV~Depth, scales = "free_y")  +
      theme(legend.position = "none",
             axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12))
  
  box2 <-  df %>% 
    filter(row(.) > 10 & row(.) <= 20) %>%
    left_join(pseq %>% psmelt.dplyr() %>% rename(ASV = OTU)) %>% 
    mutate(ASV = str_remove(ASV, "b_asv_")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(ASV = fct_inorder(ASV)) %>%
    ggplot(aes(site, Abundance, fill = site)) +
    geom_jitter(alpha = 0.5, width = 0.1) +
    geom_boxplot(alpha = 0.5) +
    scale_fill_manual(values = cage_control) +
   # labs(y = "Abundance (CLR)") +
    theme(axis.title.x = element_blank()) +
  #  scale_color_manual(values = cage_control) +
    facet_grid(ASV~Depth, scales = "free_y")  +
      theme(legend.position = "none",
            axis.title.y = element_blank(),
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12))
  
  box_vip <- box1 + box2

  return(box_vip)

}

nest_vip <- rf_NH4[[4]] %>%
  mutate(env_par = "NH4") %>%
  bind_rows(rf_NOX[[4]] %>% 
  mutate(env_par = "NOX"),
  rf_oxygen[[4]] %>% 
  mutate(env_par = "oxygen"),
  rf_turb[[4]] %>% 
  mutate(env_par = "turbidiy")) %>%
  group_by(env_par) %>%
  nest %>%
  mutate(plots = map2(data,env_par, ~box_vip(.x) + 
                        plot_annotation(title = paste(.y))
                      ))


walk2(nest_vip$env_par, nest_vip$plots,
    ~ggsave(filename = paste0(folder_path,"plots/random_forest/vip_boxplot_rf_",.x, ".tiff"), 
            plot = .y, 
            height = 15, 
            width = 15, 
            compression = "lzw"))

tax_to_italics <- function(psmelt){
  psmelt %>% 
    mutate(Family.ital = ifelse(Family %in% fams.italy,
                                 str_c('*', Family, '*'),
                                 as.character(Family)),
            Genus.ital = ifelse(Genus %in% genus.italy,
                                str_c('*', Genus, '*'),
                                as.character(Genus)))
}


vip_16s %>% 
  filter(env_par == "NOX") %>%
    slice_max(Importance, n=10) %>% 
    left_join(pseq %>% psmelt.dplyr() %>% 
                rename(ASV = OTU)) %>% 
    mutate(ASV = str_remove(ASV, "b_asv_")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(ASV = fct_inorder(ASV)) %>%
    ggplot(aes(site, Abundance, fill = site)) +
    geom_jitter(alpha = 0.5, width = 0.1) +
    geom_boxplot(alpha = 0.5) +
    scale_fill_manual(values = cage_control) +
    labs(y = "Abundance (CLR)") +
    theme(axis.title.x = element_blank()) +
  #  scale_color_manual(values = cage_control) +
    facet_grid(ASV~Depth, scales = "free_y")  +
      theme(legend.position = "none",
             axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 12))
  
```

## Heatmap
```{r}
library(tidyHeatmap)
library(ComplexHeatmap)

ht_vip <- function(df){

top_vip <-  df %>% 
    slice_head(n=20) %>% 
    mutate(ASV = str_remove(ASV, "b_asv_"),
           ASV = str_c(ASV, Genus, sep = "_")) %>%
 #   mutate_if(is.character, as.factor) %>%
    mutate(ASV = fct_inorder(ASV)) %>% pull(ASV)

ht <- pseq %>% 
    psmelt.dplyr() %>% 
    rename(ASV = OTU) %>% 
    mutate(ASV = str_remove(ASV, "b_asv_"),
           ASV = str_c(ASV, Genus, sep = "_")) %>%
    left_join(df) %>% filter(ASV %in% top_vip) %>%
    mutate(ASV = factor(ASV),
           ASV = fct_relevel(ASV, levels(top_vip)))  %>% 
#  mutate(Depth = fct_relevel(Depth, c("DP1", "DP2", "DP3"))) %>%
  #group_by(site) %>%
  heatmap(.column = Sample, 
          .row = ASV,
          .value = Abundance,
          column_km = 2,
          # row_km = 2,
          palette_value = circlize::colorRamp2(c(-4,  -1, 0, 1, 4), viridis::magma(5)),
          column_names_gp = grid::gpar(fontsize = 7.5),
          row_names_gp = grid::gpar(fontsize = 11, fontface = "italic"),
          column_names_rot = -45,
          cluster_rows=FALSE,
         # column_title_gp = grid::gpar(fontsize = 3),
         # palette_grouping = list(c("#66C2A5", "#FC8D62"))
          ) %>%
  add_tile(Family,palette = friendly_cols) %>%
  add_tile(Depth, palette = color_depth) %>%
  add_tile(site, palette = cage_control) 

return(ht)

}

ht_vip(rf_NH4[[4]])

nest_vip_ht <- rf_NH4[[4]] %>%
  mutate(env_par = "NH4") %>%
  bind_rows(rf_NOX[[4]] %>% 
  mutate(env_par = "NOX"),
  rf_oxygen[[4]] %>% 
  mutate(env_par = "oxygen"),
  rf_turb[[4]] %>% 
  mutate(env_par = "turbidiy")) %>%
  group_by(env_par) %>%
  nest %>%
  mutate(plots = map(data, ~ht_vip(.x)))

tiff(filename = paste0(folder_path,"plots/random_forest/heatmap_NH4.tiff"), compression = "lzw", width = 15.8, height = 7.8, units = "in", res = 300)
nest_vip_ht$plots[[1]]
dev.off()

tiff(filename = paste0(folder_path,"plots/random_forest/heatmap_NOX.tiff"), compression = "lzw", width = 15.8, height = 7.8, units = "in", res = 300)
nest_vip_ht$plots[[2]]
dev.off()

tiff(filename = paste0(folder_path,"plots/random_forest/heatmap_oxygen.tiff"), compression = "lzw", width = 15.8, height = 7.8, units = "in", res = 300)
nest_vip_ht$plots[[3]]
dev.off()

tiff(filename = paste0(folder_path,"plots/random_forest/heatmap_turbidity.tiff"), compression = "lzw", width = 15.8, height = 7.8, units = "in", res = 300)
nest_vip_ht$plots[[4]]
dev.off()

```


